# Generated by Django 5.2.17 on 2026-08-11 11:25

import django.core.validators
import django.db.models.deletion
import recipes.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='название')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('servings', models.PositiveSmallIntegerField(default=2, verbose_name='порций')),
                ('prep_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='подготовка, минут')),
                ('cook_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='приготовление, минут')),
                ('cover', models.ImageField(blank=True, upload_to='recipes/covers/%Y/%m/', validators=[recipes.validators.validate_recipe_image], verbose_name='фотография блюда')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='ингредиент')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='количество')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='единица')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='примечание')),
                ('search_query', models.CharField(blank=True, help_text='Если оставить пустым, будет использовано название ингредиента.', max_length=240, verbose_name='запрос для Лавки')),
                ('optional', models.BooleanField(default=False, verbose_name='необязательный')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='заголовок')),
                ('instruction', models.TextField(verbose_name='инструкция')),
                ('image', models.ImageField(blank=True, upload_to='recipes/steps/%Y/%m/', validators=[recipes.validators.validate_recipe_image], verbose_name='фотография шага')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'шаг',
                'verbose_name_plural': 'шаги',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
