# Generated by Django 5.2.17 on 2026-08-11 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, max_length=2048, verbose_name='источник'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], db_index=True, default='published', max_length=16, verbose_name='статус'),
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2048, verbose_name='ссылка')),
                ('source_type', models.CharField(choices=[('website', 'Сайт'), ('youtube', 'YouTube')], max_length=16, verbose_name='тип источника')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обрабатывается'), ('completed', 'Готово'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16, verbose_name='статус')),
                ('source_title', models.CharField(blank=True, max_length=300, verbose_name='название источника')),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('recipe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_job', to='recipes.recipe')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'импорт рецепта',
                'verbose_name_plural': 'импорты рецептов',
                'ordering': ['-created_at'],
            },
        ),
    ]
