# Generated by Django 5.2.17 on 2026-08-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_source_url_recipe_status_importjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='estimated',
            field=models.BooleanField(default=False, help_text='Отметьте, если точного количества не было в источнике.', verbose_name='количество примерное'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='section',
            field=models.CharField(blank=True, help_text='Например, «Для супа» или «Для гренок».', max_length=120, verbose_name='раздел'),
        ),
    ]
