# Generated by Django 5.2.17 on 2026-08-11 12:38

from django.db import migrations, models


def seed_categories(apps, schema_editor):
    Category = apps.get_model("recipes", "Category")
    categories = (
        ("breakfast", "Завтрак"),
        ("appetizer", "Закуска"),
        ("soup", "Суп"),
        ("salad", "Салат"),
        ("main-course", "Второе блюдо"),
        ("side-dish", "Гарнир"),
        ("bakery", "Выпечка"),
        ("dessert", "Десерт"),
        ("drink", "Напиток"),
        ("sauce", "Соус"),
        ("preserve", "Заготовка"),
        ("other", "Другое"),
    )
    Category.objects.bulk_create(
        [Category(slug=slug, name=name, order=index) for index, (slug, name) in enumerate(categories)]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeingredient_estimated_recipeingredient_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='название')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.category', verbose_name='категории'),
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
