# Generated by Django 5.2.17 on 2026-08-11 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_category_recipe_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(choices=[('auchan', 'Ашан'), ('perekrestok', 'Перекрёсток'), ('pyaterochka', 'Пятёрочка'), ('magnit', 'Магнит'), ('lavka', 'Яндекс Лавка')], max_length=24, verbose_name='магазин')),
                ('status', models.CharField(choices=[('processing', 'Поиск'), ('exact', 'Все продукты найдены'), ('substitutions', 'Есть замены'), ('incomplete', 'Не всё найдено'), ('login_required', 'Нужен вход'), ('blocked', 'Сайт заблокировал браузер'), ('failed', 'Ошибка')], default='processing', max_length=24, verbose_name='статус')),
                ('cart_url', models.URLField(blank=True, max_length=2048, verbose_name='ссылка на корзину')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='результат')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='ответ агента')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'попытка сборки корзины',
                'verbose_name_plural': 'попытки сборки корзины',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItemMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=180, verbose_name='ингредиент')),
                ('requested_quantity', models.CharField(blank=True, max_length=80, verbose_name='нужно')),
                ('product_name', models.CharField(blank=True, max_length=300, verbose_name='выбранный товар')),
                ('product_url', models.URLField(blank=True, max_length=2048, verbose_name='ссылка на товар')),
                ('package_count', models.PositiveSmallIntegerField(default=0, verbose_name='упаковок')),
                ('quality', models.CharField(choices=[('exact', 'Точное совпадение'), ('substitute', 'Замена'), ('missing', 'Не найдено')], max_length=16, verbose_name='качество совпадения')),
                ('warning', models.CharField(blank=True, max_length=500, verbose_name='предупреждение')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='recipes.cartattempt')),
            ],
            options={
                'verbose_name': 'подбор товара',
                'verbose_name_plural': 'подборы товаров',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CartRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.PositiveSmallIntegerField(verbose_name='порций')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Собирается'), ('completed', 'Корзина готова'), ('review', 'Нужна проверка'), ('login_required', 'Нужен вход'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=24, verbose_name='статус')),
                ('store_priority', models.JSONField(default=list, verbose_name='очередь магазинов')),
                ('ingredient_snapshot', models.JSONField(default=list, verbose_name='ингредиенты')),
                ('next_store_index', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_runs', to='recipes.recipe')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_runs', to=settings.AUTH_USER_MODEL)),
                ('selected_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_runs', to='recipes.cartattempt')),
            ],
            options={
                'verbose_name': 'сборка корзины',
                'verbose_name_plural': 'сборки корзин',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cartattempt',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='recipes.cartrun'),
        ),
        migrations.CreateModel(
            name='StorePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(choices=[('auchan', 'Ашан'), ('perekrestok', 'Перекрёсток'), ('pyaterochka', 'Пятёрочка'), ('magnit', 'Магнит'), ('lavka', 'Яндекс Лавка')], max_length=24, verbose_name='магазин')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='приоритет')),
                ('enabled', models.BooleanField(default=True, verbose_name='использовать')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'приоритет магазина',
                'verbose_name_plural': 'приоритеты магазинов',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='cartattempt',
            constraint=models.UniqueConstraint(fields=('run', 'store'), name='unique_store_attempt_per_run'),
        ),
        migrations.AddConstraint(
            model_name='storepreference',
            constraint=models.UniqueConstraint(fields=('user', 'store'), name='unique_store_preference_per_user'),
        ),
    ]
