# Generated by Django 5.2.17 on 2026-08-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipestep_video_timestamp_seconds'),
        ('recipes', '0012_alter_browserloginsession_user'),
    ]

    operations = [
    ]
