# Generated by Django 5.2.17 on 2026-08-13 21:38

from django.conf import settings
from django.db import migrations, models


def select_one_store_per_user(apps, schema_editor):
    StorePreference = apps.get_model("recipes", "StorePreference")
    StorePreference.objects.update(
        legacy_enabled_before_single_selection=models.F("enabled")
    )
    user_ids = StorePreference.objects.values_list("user_id", flat=True).distinct()
    for user_id in user_ids.iterator():
        preferences = list(
            StorePreference.objects.filter(user_id=user_id).order_by("position", "pk")
        )
        if not preferences:
            continue
        selected = next((item for item in preferences if item.enabled), preferences[0])
        StorePreference.objects.filter(user_id=user_id).update(enabled=False)
        StorePreference.objects.filter(pk=selected.pk).update(enabled=True)


def restore_legacy_store_selection(apps, schema_editor):
    StorePreference = apps.get_model("recipes", "StorePreference")
    StorePreference.objects.filter(
        legacy_enabled_before_single_selection__isnull=False
    ).update(enabled=models.F("legacy_enabled_before_single_selection"))


class Migration(migrations.Migration):
    # PostgreSQL cannot create the partial unique index while the preceding
    # data migration has pending trigger events in the same transaction.
    # Let Django commit each operation before advancing to the constraint.
    atomic = False

    dependencies = [
        ('recipes', '0014_merge_reciperefinement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storepreference',
            name='legacy_enabled_before_single_selection',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AlterModelOptions(
            name='storepreference',
            options={'ordering': ['position', 'pk'], 'verbose_name': 'магазин пользователя', 'verbose_name_plural': 'магазины пользователей'},
        ),
        migrations.AlterField(
            model_name='cartattempt',
            name='store',
            field=models.CharField(choices=[('auchan', 'Ашан'), ('perekrestok', 'Перекрёсток'), ('pyaterochka', 'Пятёрочка'), ('magnit', 'Магнит'), ('lavka', 'Яндекс Лавка')], max_length=24, verbose_name='магазин'),
        ),
        migrations.AlterField(
            model_name='storepreference',
            name='store',
            field=models.CharField(choices=[('auchan', 'Ашан'), ('perekrestok', 'Перекрёсток'), ('pyaterochka', 'Пятёрочка'), ('magnit', 'Магнит'), ('lavka', 'Яндекс Лавка')], max_length=24, verbose_name='магазин'),
        ),
        migrations.RunPython(select_one_store_per_user, restore_legacy_store_selection),
        migrations.AddConstraint(
            model_name='storepreference',
            constraint=models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('user',), name='unique_selected_store_per_user'),
        ),
    ]
