# Generated by Django 5.2.17 on 2026-08-13 21:38

from django.conf import settings
from django.db import migrations, models


def select_one_store_per_user(apps, schema_editor):
    StorePreference = apps.get_model("recipes", "StorePreference")
    user_ids = StorePreference.objects.values_list("user_id", flat=True).distinct()
    for user_id in user_ids.iterator():
        preferences = list(
            StorePreference.objects.filter(user_id=user_id).order_by("position", "pk")
        )
        if not preferences:
            continue
        selected = next((item for item in preferences if item.enabled), preferences[0])
        StorePreference.objects.filter(user_id=user_id).update(enabled=False)
        StorePreference.objects.filter(pk=selected.pk).update(enabled=True)


def restore_legacy_store_selection(apps, schema_editor):
    StorePreference = apps.get_model("recipes", "StorePreference")
    # The legacy pipeline accepted multiple enabled stores. Enabling every
    # existing preference gives a rolled-back application a complete fallback
    # list instead of silently limiting it to the single new-style selection.
    StorePreference.objects.update(enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_merge_reciperefinement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storepreference',
            options={'ordering': ['position', 'pk'], 'verbose_name': 'магазин пользователя', 'verbose_name_plural': 'магазины пользователей'},
        ),
        migrations.AlterField(
            model_name='cartattempt',
            name='store',
            field=models.CharField(choices=[('auchan', 'Ашан'), ('perekrestok', 'Перекрёсток'), ('pyaterochka', 'Пятёрочка'), ('magnit', 'Магнит'), ('lavka', 'Яндекс Лавка')], max_length=24, verbose_name='магазин'),
        ),
        migrations.AlterField(
            model_name='storepreference',
            name='store',
            field=models.CharField(choices=[('auchan', 'Ашан'), ('perekrestok', 'Перекрёсток'), ('pyaterochka', 'Пятёрочка'), ('magnit', 'Магнит'), ('lavka', 'Яндекс Лавка')], max_length=24, verbose_name='магазин'),
        ),
        migrations.RunPython(select_one_store_per_user, restore_legacy_store_selection),
        migrations.AddConstraint(
            model_name='storepreference',
            constraint=models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('user',), name='unique_selected_store_per_user'),
        ),
    ]
