# Generated by Django 5.2 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0015_alter_storepreference_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartrun",
            name="cancellation_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
