# Generated by Django 5.2 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0016_cartrun_cancellation_requested_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartrun",
            name="browser_operation_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
