# Generated by Django 5.2.17 on 2026-09-07 14:18

from urllib.parse import urlsplit

from django.db import migrations, models


def copy_source_links(apps, schema_editor):
    Recipe = apps.get_model("recipes", "Recipe")
    recipes = Recipe.objects.using(schema_editor.connection.alias)
    for recipe in recipes.exclude(source_url="").iterator():
        try:
            host = (urlsplit(recipe.source_url).hostname or "").lower()
        except ValueError:
            host = ""
        is_video = host in {
            "youtu.be", "www.youtu.be", "youtube.com", "www.youtube.com",
            "m.youtube.com", "music.youtube.com",
        }
        field = "video_url" if is_video else "text_source_url"
        recipes.filter(pk=recipe.pk).update(**{field: recipe.source_url})


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_browserloginsession_transition_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='text_source_url',
            field=models.URLField(blank=True, max_length=2048, verbose_name='ссылка на исходный текст'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_url',
            field=models.URLField(blank=True, max_length=2048, verbose_name='ссылка на видео'),
        ),
        migrations.RunPython(copy_source_links, migrations.RunPython.noop),
    ]
